image: docker:latest

variables:
  GOOGLE_TAG: eu.gcr.io/papers-kubernetes/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHA
  GOOGLE_TAG_LATEST: eu.gcr.io/papers-kubernetes/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest

stages:
  - build
  - test
#  - publish

build:
  stage: build
  variables:
    BUILD_CONTAINER: build-$CI_COMMIT_SHA
  before_script:
    - docker rm -f $BUILD_CONTAINER || true
  script:
    - docker build -t $GOOGLE_TAG .
    - docker run --name $BUILD_CONTAINER $GOOGLE_TAG echo "container ran"
    - docker cp $BUILD_CONTAINER:/build/android-core-release-unsigned.aar beaconsdk-core-release-unsigned-$CI_PIPELINE_ID.aar
  after_script:
    - docker rm -f $BUILD_CONTAINER || true
  tags:
    - docker
  artifacts:
    paths:
      - beaconsdk-core-release-unsigned-$CI_PIPELINE_ID.aar

unit:
  stage: test
  variables:
    UNIT_CONTAINER: unit-$CI_COMMIT_SHA
    LINT_CONTAINER: lint-$CI_COMMIT_SHA
  before_script:
    - docker rm -f $UNIT_CONTAINER || true
    - docker rm -f $LINT_CONTAINER || true
  script:
    - docker run --name $UNIT_CONTAINER $GOOGLE_TAG /bin/bash -c "/build/gradlew --project-dir /build --info testMockReleaseUnitTest"
    - docker cp $UNIT_CONTAINER:/build/core/build/reports/tests/testMockReleaseUnitTest unit-test-report-$CI_PIPELINE_ID
    - docker run --name $LINT_CONTAINER $GOOGLE_TAG /bin/bash -c "/build/gradlew --project-dir /build lint"
    - docker cp $LINT_CONTAINER:/build/core/build/reports/lint-results.html lint-report-$CI_PIPELINE_ID.html
  after_script:
    - docker rm -f $UNIT_CONTAINER || true
    - docker rm -f $LINT_CONTAINER || true
  tags:
    - docker
  artifacts:
    paths:
      - unit-test-report-$CI_PIPELINE_ID
      - lint-report-$CI_PIPELINE_ID.html